### ISSUE TITLE
Example for multi upload and add photo set?

### ISSUE THREAD

**Issue by dimxasy** [samwilson/phpflickr#11]
Hello everyone and the author,

Can you help me for example of multi upload and add photo set after upload? I tried it but it responded like this.

I can pay for it to show gratitude.

Thanks for that!
![47684705_1269029973239038_7721016897898020864_n](https://user-images.githubusercontent.com/45124974/49812918-07f32900-fd99-11e8-97d3-9b4744a5d33b.png)

**Comment by samwilson** [comment]
Sorry about not replying to this. Do you still need help with it?
