### ISSUE TITLE
Setproxy throws an uncaught error

### ISSUE THREAD

**Issue by Daltonmedia** [samwilson/phpflickr#22]
Hey,

$f->setProxy("localhost", "8181"); is giving me a: `Fatal error: Uncaught Error: Call to a member function setProxy() on null in /home/my/domain/public_html/FA/src/PhpFlickr.php:398`

Any idea what this could be? I'm sure the proxy works.
Thanks

**Comment by samwilson** [comment]
The proxy feature is not functioning with OAuth requests yet, sorry!

I'll try to find time to fix this soon.

**Comment by samwilson** [comment]
This should work now. Read the docs for how (it's slightly different).
