### ISSUE TITLE
Not Getting "oauth_verifier" From $flickr->getAuthUrl($perm, $callbackUrl);

### ISSUE THREAD

**Issue by testingCitytech** [samwilson/phpflickr#24]
**This is my code:**

`require_once 'vendor/autoload.php';
$apiKey = "6cc27cfb0c759011b11a48e456d8ba74";
$apiSecret = "6169a34168fae718";
$flickr = new \Samwilson\PhpFlickr\PhpFlickr($apiKey, $apiSecret);

$storage = new \OAuth\Common\Storage\Memory();
$flickr->setOauthStorage($storage);

$perm = 'write';
$callbackUrl = false;
$url = $flickr->getAuthUrl($perm, $callbackUrl);`

am not getting 'oauth_verifier' From $flickr->getAuthUrl($perm, $callbackUrl); 

**My Output**

`OAuth\Common\Http\Uri\Uri Object
(
    [scheme:OAuth\Common\Http\Uri\Uri:private] => https
    [userInfo:OAuth\Common\Http\Uri\Uri:private] => 
    [rawUserInfo:OAuth\Common\Http\Uri\Uri:private] => 
    [host:OAuth\Common\Http\Uri\Uri:private] => api.flickr.com
    [port:OAuth\Common\Http\Uri\Uri:private] => 443
    [path:OAuth\Common\Http\Uri\Uri:private] => /services/oauth/authorize
    [query:OAuth\Common\Http\Uri\Uri:private] => oauth_token=72157710566803341-1250e3b8a7496c87&perms=write
    [fragment:OAuth\Common\Http\Uri\Uri:private] => 
    [explicitPortSpecified:OAuth\Common\Http\Uri\Uri:private] => 
    [explicitTrailingHostSlash:OAuth\Common\Http\Uri\Uri:private] => 
)`

How to get 'oauth_token' from this array?
![demo php](https://user-images.githubusercontent.com/54580411/63765395-8a4f5900-c8e6-11e9-8c08-01f8c9e8266d.png)

**Comment by samwilson** [comment]
Your `$url` object is not an array, it's a `\OAuth\Common\Http\Uri\Uri` object. You normally don't need to get just the `oauth_verifier` value at this point, but rather the whole URL to which to send your user. This can be cast to a string, to get the full URL. You could for example redirect a web browser user like this:

```php
header("Location: $url");
```

**Comment by samwilson** [comment]
(Oh, and you should delete your `6cc27cfb0c759011b11a48e456d8ba74` API key, as its secret has now been published publicly.)

**Comment by testingCitytech** [comment]
@samwilson  Thank you.
it is working but when I click "OK, I'LL AUTHORIZE IT" button not redirect to another page. 
![Flickr  Authorize Upload Photo](https://user-images.githubusercontent.com/54580411/63851757-5fcbd180-c9b4-11e9-99d7-287640787e50.png)

Please help me...
This API Key is invalid just for example.

**Comment by samwilson** [comment]
That's because you're passing `false` as the `$callbackUrl`. What happens when you try [examples/get_auth_token.php](https://github.com/samwilson/phpflickr/blob/master/examples/get_auth_token.php) in the browser? Does it work? That code adds a callback URL of itself. (Note that you need to create `examples/config.php` before using the examples.)

**Comment by testingCitytech** [comment]
This is `index.php` 

`
require_once 'vendor/autoload.php';

$apiKey = "6cc27cfb0c759011b11a48e456d8ba8d";
$apiSecret = "6169a34168fae6b8";
$flickr = new \Samwilson\PhpFlickr\PhpFlickr($apiKey, $apiSecret);

$storage = new \OAuth\Common\Storage\Memory();
$flickr->setOauthStorage($storage);

$perm = 'write';
$callbackUrl = 'http://localhost/flickr/get_token.php';
$url = $flickr->getAuthUrl($perm, $callbackUrl);
header("Location: $url");`

![Flickr  Authorize Upload Photo](https://user-images.githubusercontent.com/54580411/63931950-e5628680-ca73-11e9-8ba4-949c36315f27.png)

This is `get_token.php`

`require_once 'vendor/autoload.php';

$apiKey = "6cc27cfb0c759011b11a48e456d8ba8d";
$apiSecret = "6169a34168fae6b8";
$flickr = new \Samwilson\PhpFlickr\PhpFlickr($apiKey, $apiSecret);
$flickr->auth("write");
$accessToken = $flickr->retrieveAccessToken($_GET['oauth_verifier'], $_GET['oauth_token']);`

![Flickr Services 2](https://user-images.githubusercontent.com/54580411/63932090-1d69c980-ca74-11e9-89ee-ee3b761a0a40.png)

now what to do?

**Comment by samwilson** [comment]
Did you create `examples/config.php` with valid values?

**Comment by samwilson** [comment]
Is this working now?
