### ISSUE TITLE
New 6K display size support

### ISSUE THREAD

**Issue by gegere** [samwilson/phpflickr#25]
Greetings Sam, a question about the 6K image support flickr is offering to Pro members. Any additional information on this?

**Comment by samwilson** [comment]
I'm not sure. I haven't heard anything about the API changing. Surely they'll just be treated as normal photos as regards metadata etc.? It's just front-end display stuff that you might want to adjust.

**Comment by gegere** [comment]
More info: https://www.flickr.com/help/forum/en-us/72157710955873986/

**Comment by samwilson** [comment]
I think `PhotosApi::getSizes()` will work fine and return the new larger size for photos where it's available, but Flickr haven't updated the [list of size codes](https://www.flickr.com/services/api/misc.urls.html) yet. So I don't think anything needs to be done here. I'll keep an eye on it though, and thanks for the heads-up!

**Comment by samwilson** [comment]
It doesn't look like anything needs to change with this library at this point.
