### ISSUE TITLE
Too few arguments to function Samwilson\PhpFlickr\PhotosApi::search()

### ISSUE THREAD

**Issue by sultan-rex** [samwilson/phpflickr#43]
when I send an array argument to photos_search function , it throws this error

Too few arguments to function Samwilson\PhpFlickr\PhotosApi::search(), 0 passed in C:\xampp\htdocs\gallery\vendor\samwilson\phpflickr\src\PhpFlickr.php on line 1376 and exactly 1 expected

For this line

`$photos = $flickr->photos_search(array(
            'api_key' => 'dfghddfd',
            'tags' => 'cars'
        ));`

**Comment by ZiTAL** [comment]
photos_search is deprecated, use:
```
$photos = $flickr->photos()->search(array( 'api_key' => 'dfghddfd', 'tags' => 'cars' ));
```

**Comment by samwilson** [comment]
It's true that it's deprecated, but it should've kept working anyway. I've just fixed this issue (although, there's no need to use the fix!).
