### ISSUE TITLE
dependency issue upgrading to Symfony 6.2

### ISSUE THREAD

**Issue by mcrauwel** [samwilson/phpflickr#55]
Symfony 6.2 requires `psr/cache` `^2` or `^3` while phpflickr requires `psr/cache` `^1`

Composer update snippets...
When upgrading from Symfony 5.4 to 6.2
```
    - symfony/cache[v6.2.0, ..., v6.2.4] require psr/cache ^2.0|^3.0 -> found psr/cache[2.0.0, 3.0.0] but it conflicts with your root composer.json require (^1).
```

When changing the requirement for `psr/cache` from `^1` -> `^3`
```
    - samwilson/phpflickr[4.14.0, ..., 4.14.3] require psr/cache ^1.0 -> found psr/cache[1.0.0, 1.0.1] but it conflicts with your root composer.json require (3.*).
```

**Comment by samwilson** [comment]
Hmm. Maybe we can do `"psr/cache": "^1|^2|^3"`? What are the non-BC changes that they've made to the psr/cache API? I think we're using only `CacheItemPoolInterface::getItem()`, `CacheItemPoolInterface::save()`, `CacheItemInterface::set()` and `CacheItemInterface::expiresAfter()`.

**Comment by mcrauwel** [comment]
Looking at the releases page, they compatibility to PHP8 in [version 2](https://github.com/php-fig/cache/releases/tag/2.0.0)
And they added return types in [version 3](https://github.com/php-fig/cache/releases/tag/3.0.0)

**Comment by samwilson** [comment]
Well that sounds hopeful. I'll test later and see how it goes. Maybe it'll be super simple. :-)

**Comment by samwilson** [comment]
I've updated the psr/cache version requirement, see what you think of #56.

**Comment by mcrauwel** [comment]
that does the trick!

```
-        "psr/cache": "^1",
+        "psr/cache": "^3",
         "psr/log": "^1",
         "ruudvdd/ogm": "^0.2.0",
-        "samwilson/phpflickr": "^4.14",
+        "samwilson/phpflickr": "dev-cache-update",
         "sensio/framework-extra-bundle": "^6.1",
         "symfony/apache-pack": "^1.0",
-        "symfony/asset": "5.4.*",
-        "symfony/console": "5.4.*",
-        "symfony/dotenv": "5.4.*",
-        "symfony/expression-language": "5.4.*",
+        "symfony/asset": "6.2.*",
+        "symfony/console": "6.2.*",
+        "symfony/dotenv": "6.2.*",
+        "symfony/expression-language": "6.2.*",
...
```

works like a charm!

**Comment by samwilson** [comment]
Great, thanks for testing. I've made a new release.

**Comment by mcrauwel** [comment]
🙇
