### ISSUE TITLE
ticket-ids have hyphens, cast to string instead of int.

### ISSUE THREAD

**Issue by tacman** [samwilson/phpflickr#71]
Can you add an async example to either here or the phpflickr-cli repo?

I _think_ there's a bug on Flickr itself, get a ticketid back but when I try to get the status via checkTickets it says the ticketid is invalid.

https://www.reddit.com/r/flickr/comments/1e78y9z/async_upload_api_not_returning_valid_ticketid/

Have you had any issues with async?

**Comment by tacman** [comment]
Ticket ids have a hypen, will submit a PR.

ticketid": "200775939-72157722968227621"

**Comment by samwilson** [comment]
Thanks for digging into it, and for the fix.
