### ISSUE TITLE
some deprecations

### ISSUE THREAD

**Issue by tacman** [samwilson/phpflickr#79]
I saw these.  I think it's okay to simply follow the suggestions, but can't remember exactly if they'd work for PHP 7.2.  

![image](https://github.com/user-attachments/assets/f4828e9e-20c4-4da0-9329-ab663d8ce065)

**Comment by samwilson** [comment]
With the addition of UriInterface as a return type hint, Phan is now complaining:

> src/Oauth/PhpFlickrService.php:39 PhanUndeclaredTypeReturnType Return type of getRequestTokenEndpoint() is undeclared type \OAuth\Common\Http\Uri\UriInterface

> src/Oauth/PhpFlickrService.php:41 PhanTypeMismatchReturn Returning new Uri((static::$baseUrl . '/oauth/request_token')) of type \OAuth\Common\Http\Uri\Uri but getRequestTokenEndpoint() is declared to return \OAuth\Common\Http\Uri\UriInterface

**Comment by tacman** [comment]
Yeah, I just ran into phpstan complaining in another project.  I'm never quite sure when to return self, static or the class/interface name itself.

**Comment by samwilson** [comment]
It's a bit strange. It's like Phan is not loading vendor classes, but it must be because surely otherwise it'd be complaining about a bunch of other stuff.

**Comment by samwilson** [comment]
Oh, Phan was not loading the vendor directory! Fixing now.
