### ISSUE TITLE
help please, photoset_getlist returns no photosets

### ISSUE THREAD

**Issue by grangep** [samwilson/phpflickr#9]
I was using the original Dan Coulter library which worked for me, but is reporting errors on php7.2 so I installed this version via composer. However photoset_getlist returns no no photosets. No error, just 0 photosets. The old version returns the photosets I was expecting. Any suggestions please?

**Comment by gegere** [comment]
Try managing PHP Composer without the dev libs, I had a similar issue.

Run the following in the same directory as `composer.json`
$ composer install --no-dev

**Comment by grangep** [comment]
Thanks for your comment. I'm bogged down in another project for some time to come, but will try this as soon as I can get back to the project with this issue.

**Comment by samwilson** [comment]
Closing this, but feel free to open a new issue if you're still having problems.
